server:
  port: ${PORT:8761}

eureka:
  instance: 
    hostname: localhost
    metadataMap.zone: "rcnet-zone-1"
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 20
